import type { Metadata } from "next";
import localFont from "next/font/local";

import MainLayout from "@/components/layouts/MainLayout";


// ---------import css--------------

import "@/styles/bootstrap.min.css"
import "@/styles/magnific-popup.css"
import "@/styles/magnific-popup.css"
import "@/styles/slick.css"
import "@/styles/style.css"
import "@/styles/responsive.css"

import "@/styles/fontawsome/css/all.min.css"
import "@/styles/fontawsome/css/fontawesome.min.css"
import '@/styles/work-experience.css'

// -----------------------------------------------------


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MainLayout>
          {children}
        </MainLayout>
      </body>
    </html>
  );
}
